### ISSUE TITLE
v0.4.0 MacOS LateInitializationError

### ISSUE THREAD

**Issue by AlphaBlend1975** [woodemi/quick.flutter#41]
After update to 0.4.0 
My mac error when running app 

[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: LateInitializationError: Field '_libusb@1709324630' has not been initialized.
#0      _libusb (package:quick_usb/src/quick_usb_desktop.dart)
#1      _QuickUsbDesktop.init (package:quick_usb/src/quick_usb_desktop.dart:44:12)
#2      QuickUsb.init (package:quick_usb/quick_usb.dart:13:43)
#3      main (package:qipos/main.dart:44:20)
#4      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:130:25)
#5      _rootRun (dart:async/zone.dart:1426:13)
#6      _CustomZone.run (dart:async/zone.dart:1328:19)
#7      _runZoned (dart:async/zone.dart:1861:10)
#8      runZonedGuarded (dart:async/zone.dart:1849:12)
#9      _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:126:5)
#10     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)

[SOLUTION]
Rollback to 0.3.1 work fine

**Comment by iharshb** [comment]
@AlphaBlend1975 I am still getting zero length of getDevices(). Did you get any solution for this?

`  await QuickUsb.init();
      var detectedList = await QuickUsb.getDevicesWithDescription();`

**Comment by Sunbreak** [comment]
Clean cache in `.dart_tool` may help according to https://github.com/woodemi/quick_blue/issues/102#issuecomment-1119171251
