### ISSUE TITLE
Throws error LIBUSB_ERROR_NOT_FOUND

### ISSUE THREAD

**Issue by xaldarof** [woodemi/quick.flutter#45]
[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: getConfigDesc error: LIBUSB_ERROR_NOT_FOUND
#0      _QuickUsbDesktop.getConfiguration (package:quick_usb/src/quick_usb_desktop.dart:198:9)
#1      QuickUsb.getConfiguration (package:quick_usb/quick_usb.dart:49:17)
#2      _PrinterAppState.build.<anonymous closure>.<anonymous closure> (package:printer_example/main.dart:207:62)
<asynchronous suspension>

**Comment by Sunbreak** [comment]
https://github.com/woodemi/libusb.dart is a simple wrapper of https://github.com/libusb/libusb

You need to learn about libusb's feature to solve above error
