### ISSUE TITLE
[quick_usb] Mac M1 library loading issue

### ISSUE THREAD

**Issue by mjafartp** [woodemi/quick.flutter#56]
in MAc M1 it shows an error because of no library for arm64e

[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library 'libusb-1.0.23.dylib': dlopen(libusb-1.0.23.dylib, 0x0001): tried: '/Users/xxx/apps/xxxa/apps/xxxa/build/macos/Build/Products/Debug/xxxa.app/Contents/Frameworks/FlutterMacOS.framework/Versions/A/./libusb-1.0.23.dylib' (no such file), '/Users/xxx/apps/xxxa/apps/xxxa/build/macos/Build/Products/Debug/xxxa.app/Contents/Frameworks/FlutterMacOS.framework/Versions/A/../../../libusb-1.0.23.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/lib/swift/libusb-1.0.23.dylib' (no such file), '/usr/lib/swift/libusb-1.0.23.dylib' (no such file), '/Users/xxx/apps/xxxa/apps/xxxa/build/macos/Build/Products/Debug/xxxa.app/Contents/MacOS/../Frameworks/libusb-1.0.23.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/Users/xxx/apps/xxxa/apps/xxxa/build/macos/Build/Products/Debug/xxxa.app/Contents/MacOS/Frameworks/libusb-1.0.23.dylib' (no such file), '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx/libusb-1.0.23.dylib' (no such file), '/Users/xxx/apps/xxxa/apps/xxxa/build/macos/Build/Products/Debug/xxxa.app/Contents/MacOS/../Frameworks/libusb-1.0.23.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), 'libusb-1.0.23.dylib' (no such file), '/usr/local/lib/libusb-1.0.23.dylib' (no such file), '/usr/lib/libusb-1.0.23.dylib' (no such file), '/Users/xxx/Library/Containers/AA0A2AB2-FA78-4C6B-A651-/Data/libusb-1.0.23.dylib' (no such file)
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:12:43)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:23:12)
#2      new QuickUsbMacos (package:quick_usb/src/quick_usb_desktop.dart:22:37)
#3      _platform (package:quick_usb/quick_usb.dart:25:35)
#4      QuickUsb.init (package:quick_usb/quick_usb.dart:36:33)
#5      _PrinterPopupState.getAllPrinter (package:xxxa/settings/printersPopup.dart:53:22)
#6      _PrinterPopupState.initState (package:xxxa/settings/printersPopup.dart:82:4)
#7      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4942:57)

**Comment by Sunbreak** [comment]
Googled a little. Not sure if https://github.com/libusb/libusb supports Apple Silicon or not

May try later home

**Comment by mjafartp** [comment]
[libusb](https://github.com/libusb/libusb) support apple silicon ref : [libusb](https://formulae.brew.sh/formula/libusb)
